devtools:
  restart:
   enabled=true:
server:
  port: 8083
spring:
  mail:
    username: 1448602918@qq.com
    password: wvhfyvsogogzgcdg
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/commonweal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456



#配置日志  打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


